import { Charity } from '../types';
import { CHARITY_CATEGORY } from './constants';

export const charities: Charity[] = [
  {
    id: '',
    name: 'Zrzutka',
    link: 'https://zrzutka.pl/',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.kids.value,
  },
  {
    id: '',
    name: 'One tree planted',
    link: 'https://onetreeplanted.org/',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.kids.value,
  },
  {
    id: '',
    name: 'Eden Reforestation Projects',
    link: 'https://www.edenprojects.org/',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.kids.value,
  },
  {
    id: '',
    name: 'PAH (Polska Akcja Humanitarna)',
    link: 'https://www.pah.org.pl/',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.kids.value,
  },
  {
    id: '',
    name: 'Fundacja Św. Mikołaja',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.kids.value,
  },
  {
    id: '',
    name: 'Fundacja Rak’n’roll',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.animals.value,
  },
  {
    id: '',
    name: 'Stowarzyszenie Otwarte Klatki',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.animals.value,
  },
  {
    id: '',
    name: 'Fundacja Ocalenie',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.animals.value,
  },
  {
    id: '',
    name: 'Amnesty International Polska',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.animals.value,
  },
  {
    id: '',
    name: 'WWF',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.animals.value,
  },
  {
    id: '',
    name: 'Carbon180',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.environment.value,
  },
  {
    id: '',
    name: 'Evergreen Collaborative',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.environment.value,
  },
  {
    id: '',
    name: 'Climate Foundation',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.environment.value,
  },
  {
    id: '',
    name: 'Rainforest Alliance',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.environment.value,
  },
  {
    id: '',
    name: '350.org',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.other.value,
  },
  {
    id: '',
    name: 'Fundacja Bahati',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.other.value,
  },
  {
    id: '',
    name: 'Fundacja Serce dla Zwierząt',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.other.value,
  },
  {
    id: '',
    name: 'Fundacja Czarna Owca Pana Kota',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.other.value,
  },
  {
    id: '',
    name: 'Fundacja na Rzecz Ochrony Praw Zwierząt EX LEGE',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.other.value,
  },
  {
    id: '',
    name: 'Ogólnopolska Fundacja dla Zwierząt',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.other.value,
  },
  {
    id: '',
    name: 'Fundacja Viva! Akcja dla zwierząt',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.other.value,
  },
  {
    id: '',
    name: 'https://zbieram.pl/',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.other.value,
  },
  {
    id: '',
    name: 'siepomaga.pl',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.other.value,
  },
  {
    id: '',
    name: 'unicef',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.other.value,
  },
  {
    id: '',
    name: 'Stowarzyszenie Ochrony Zwierząt Eko Straż Wrocław.',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.other.value,
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.other.value,
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.other.value,
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.other.value,
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.other.value,
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.other.value,
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.other.value,
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.other.value,
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.other.value,
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.other.value,
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.other.value,
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: CHARITY_CATEGORY.other.value,
  },
];
