import { Charity, CharityCategory } from '../types';

const charities: Charity[] = [
  {
    id: '',
    name: 'Zrzutka',
    link: 'https://zrzutka.pl/',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: 'One tree planted',
    link: 'https://onetreeplanted.org/',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: 'Eden Reforestation Projects',
    link: 'https://www.edenprojects.org/',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: 'PAH (Polska Akcja Humanitarna)',
    link: 'https://www.pah.org.pl/',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: 'Fundacja Św. Mikołaja',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: 'Fundacja Rak’n’roll',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: 'Stowarzyszenie Otwarte Klatki',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: 'Fundacja Ocalenie',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: 'Amnesty International Polska',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: 'WWF',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: 'Carbon180',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: 'Evergreen Collaborative',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: 'Climate Foundation',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: 'Rainforest Alliance',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: '350.org',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
  {
    id: '',
    name: '',
    link: '',
    logo: '',
    description: '',
    image: '',
    category: '',
  },
];
